<?php
/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-11-01 at 09:07:55.
 *
 * ***NOTE****
 *
 * Some Sys Ids are hardcoded in these tests to work with neustarint.service-now.com and will fail if run against another SN instance.
 * If the sys_id hashes have changed, these tests will fail.
 *
 * ***********
 */

require_once(__DIR__ . "/../php/global.php");



class CMDBSyncUpdateTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var CMDBSyncUpdate
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
	    // read the config file
	    $config = require("config.php");

	    $this->assertTrue($config->servicenow->site == "int", "only the int & prod version of servicenow has the correct structure.");

	    $this->object = new CMDBSyncUpdate;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers CMDBSyncUpdate::getByServerId
     */
    public function testGetByServerId()
    {
	    $result = $this->object->getByServerId("2901819a0a0a3cac01265423dfd48fa7");
		$this->assertTrue($result[0]->dv_u_cmdb === "stopcdvvt1.va.neustar.com", "the hash we sent retrieves the stopcdvvt1 host");
    }

    /**
     * @covers CMDBSyncUpdate::getBySysId
     */
    public function testGetBySysId()
    {
		$result = $this->object->getBySysId("409c21afe059b0002bd5a432afdb8028");

		$this->assertTrue(!is_null($result->dv_u_cmdb), "If we retrieve the record this shouldn't be null");
	    $this->assertTrue($result->dv_u_cmdb === "stopcdvvt1.va.neustar.com", "this u_sync_update record has stopcdvvt1 as it's host");

    }

    /**
     * @covers CMDBSyncUpdate::create
     */
    public function testCreate()
    {

	    $this->object->set("u_cmdb", "2901815c0a0a3cac016b4af62c226a25");
	    $this->object->set("u_most_recent_discovery", "2012-11-01 13:26:06");
	    $this->object->set("u_backup_directories", "/test/of/create/method");
	    $this->object->set("u_last_backup_date", "2012-11-01 13:26:06");
	    $this->object->set("u_last_sync_update", "2012-11-01 13:26:06");
		$result = $this->object->create();

	    $check = new CMDBSyncUpdate();
		$check_result = $check->getByServerId("2901815c0a0a3cac016b4af62c226a25");

	    $sys_id = $check_result[0]->get('sys_id');

	    $this->assertTrue("2901815c0a0a3cac016b4af62c226a25" == $check_result[0]->u_cmdb, "cmdb hash should match");
	    $this->assertTrue("stopcqavt1.va.neustar.com" == $check_result[0]->dv_u_cmdb, "cmdb display value should match");

		// Clean up
	    $delete = new CMDBSyncUpdate();
	    $delete->set('sys_id', $sys_id);
	    $delete->delete();

    }

    /**
     * @covers CMDBSyncUpdate::update
     */
    public function testUpdate()
    {

		$update = new CMDBSyncUpdate();
	    $result = $update->getBySysId("409c21afe059b0002bd5a432afdb8028");

	    $orig_back =  $result->get('u_backup_directories');

	    $update->set('sys_id', $result->get('sys_id'));
	    $update->set('u_backup_directories', '/TEST/UPDATED');
	    $update->update();

	    $check = new CMDBSyncUpdate();
	    $check_result = $check->getBySysId("409c21afe059b0002bd5a432afdb8028");
	    $this->assertTrue($check_result->get('u_backup_directories') === '/TEST/UPDATED', "it should now equal our newly updated value");

		// Clean up
	    $revert = new CMDBSyncUpdate();
	    $revert_result = $check->getBySysId("409c21afe059b0002bd5a432afdb8028");
	    $revert->set('sys_id', $revert_result->get('sys_id'));
	    $revert->set('u_backup_directories', $orig_back);
	    $revert->update();

    }

    /**
     * @covers CMDBSyncUpdate::delete
     */
    public function testDelete()
    {
	    // Just gotta make a record before we can delete it.
	    $this->object->set("u_cmdb", "2901815c0a0a3cac016b4af62c226a25");
	    $this->object->set("u_most_recent_discovery", "2012-11-01 13:26:06");
	    $this->object->set("u_backup_directories", "/test/of/create/method");
	    $this->object->set("u_last_backup_date", "2012-11-01 13:26:06");
	    $this->object->set("u_last_sync_update", "2012-11-01 13:26:06");
	    $result = $this->object->create();

	    $check = new CMDBSyncUpdate();
	    $check_result = $check->getByServerId("2901815c0a0a3cac016b4af62c226a25");

	    $sys_id = $check_result[0]->get('sys_id');

	    $this->assertTrue("2901815c0a0a3cac016b4af62c226a25" == $check_result[0]->u_cmdb, "cmdb hash should match");
	    $this->assertTrue("stopcqavt1.va.neustar.com" == $check_result[0]->dv_u_cmdb, "cmdb display value should match");

	    // kill that record we just made
	    $delete = new CMDBSyncUpdate();
	    $delete->set('sys_id', $sys_id);
	    $delete->delete();

	    // verify that we killed the record
	    $verify = new CMDBSyncUpdate();
	    $result = $verify->getBySysId($sys_id);

	    $this->assertTrue(is_null($result->dv_u_cmdb), "Record is deleted, we shouldn't be able to retrieve it");

    }

    /**
     * @covers CMDBSyncUpdate::updateByJson
     * @todo   Implement testUpdateByJson().
     */
    public function testUpdateByJson()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
